### ISSUE TITLE
AIA CSR presence should be in the MADT's description of the INTC

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-acpi#4]
Currently there's a bit in the hart features, but really the only thing that cares about that is whatever manages INTC, so it should be part of that description rather than needing to have a weird special case.

**Comment by vlsunil** [comment]
Yes, I have it in INTC also. I was in the process of cleaning up here. Will update. Thanks!

**Comment by vlsunil** [comment]
It is not required since AIA is mandatory for ACPI.
